# Remove the version line and fix environment variables
services:
  postgres:
    image: postgres:16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: postgres
      POSTRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/postgres
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: